#!/bin/sh -eux
make defconfig

scripts/config \
	-e CONFIG_R8169 \
	-e CONFIG_PHY_ROCKCHIP_NANENG_COMBO_PHY \
	-e CONFIG_PM_DEVFREQ_EVENT \
	-e CONFIG_CRYPTO_DEV_ROCKCHIP_DEBUG \
	-e CONFIG_UDMABUF \
	-e CONFIG_DMABUF_HEAPS \
	-e CONFIG_DMABUF_HEAPS_SYSTEM \
	-e CONFIG_DMABUF_HEAPS_CMA \
	-e CONFIG_DRM_LOAD_EDID_FIRMWARE \
	-e CONFIG_DYNAMIC_DEBUG

scripts/config \
	-m CONFIG_BINFMT_MISC \
	-m CONFIG_SND_SOC_RT5616 \
	-m CONFIG_DEVFREQ_EVENT_ROCKCHIP_DFI \
	-m CONFIG_ARM_ROCKCHIP_CPUFREQ \
	-m CONFIG_DEVFREQ_GOV_PERFORMANCE \
	-m CONFIG_DEVFREQ_GOV_POWERSAVE \
	-m CONFIG_CRYPTO_DEV_ROCKCHIP \
	-m CONFIG_VIDEO_ROCKCHIP_RGA \
	-m CONFIG_VIDEO_ROCKCHIP_ISP1 \
	-m CONFIG_VIDEO_ROCKCHIP_VDEC

make olddefconfig
