name: build

on:
  workflow_call:
    inputs:
      linux_repo:
        description: Linux Git repository to use
        type: string
        required: false
      linux_ref:
        description: Linux Git ref to use
        type: string
        required: false
      linux_arch:
        description: Linux ARCH to use
        type: string
        required: false
      linux_config:
        description: Linux config set to use
        type: string
        required: false
  workflow_dispatch:
    inputs:
      linux_repo:
        description: Linux Git repository to use
        type: string
        required: false
      linux_ref:
        description: Linux Git ref to use
        type: string
        required: false
      linux_arch:
        description: Linux ARCH to use
        type: string
        required: false
      linux_config:
        description: Linux config set to use
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/sigmaris/aarch64-linux-crossbuilder:trixie
    env:
      LINUX_REPO_WD: "${{ inputs.linux_repo }}"
      LINUX_REF_WD: "${{ inputs.linux_ref }}"
      LINUX_ARCH_WD: "${{ inputs.linux_arch }}"
      LINUX_CONFIG_WD: "${{ inputs.linux_config }}"
    permissions:
      contents: read
      actions: read
    steps:
      - name: Check out this repo
        uses: actions/checkout@v7

      - id: resolve_vars
        name: Resolve variables
        run: scripts/resolve_vars.sh

      - id: get_remote_commit
        name: Get commit on remote branch
        run: |
          git config --global --add safe.directory $(pwd)
          this_repo_commit="$(git rev-parse HEAD)"
          remote_commit=$(git ls-remote --heads '${{ steps.resolve_vars.outputs.linux_repo }}' '${{ steps.resolve_vars.outputs.linux_ref }}' | awk '{print $1}')
          echo "Remote commit: $remote_commit"
          echo '${{ toJSON(steps.resolve_vars.outputs) }}' | jq \
            --arg buildcommit "$this_repo_commit" \
            --arg linuxcommit "$remote_commit" \
            '. += {"build_commit":$buildcommit,"linux_commit":$linuxcommit}' > new_metadata.json

      - id: get_last_run
        name: Get previous run
        uses: actions/github-script@v9
        with:
          script: |
            const thisRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: thisRun.data.workflow_id,
              status: "success",
              per_page: 1,
              exclude_pull_requests: true
            });

            if (runs.data.total_count === 0) {
              console.log("No previous runs found");
              return null;
            } else {
              return runs.data.workflow_runs[0].id;
            }

      - id: get_last_metadata
        name: Get previous metadata
        if: fromJSON(steps.get_last_run.outputs.result) != null
        uses: actions/download-artifact@v8
        with:
          name: metadata.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get_last_run.outputs.result }}

      - id: export_metadata
        name: Export and update metadata
        run: |
          printf 'curr=%s\n' "$(jq -c . < new_metadata.json)" >> "$GITHUB_OUTPUT"
          if [ -f metadata.json ]
          then
            printf 'prev=%s\n' "$(jq -c . < metadata.json)" >> "$GITHUB_OUTPUT"
          else
            printf 'prev=null\n' >> "$GITHUB_OUTPUT"
          fi
          rm -f metadata.json
          mv new_metadata.json metadata.json

      - name: Check out linux source
        if: fromJSON(steps.export_metadata.outputs.prev) != fromJSON(steps.export_metadata.outputs.curr)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git clone --depth 1 --single-branch --branch '${{ steps.resolve_vars.outputs.linux_ref }}' '${{ steps.resolve_vars.outputs.linux_repo }}' linux-src
          cd linux-src
          # Overwrite metadata.json with what was actually cloned in case it differs:
          echo '${{ toJSON(steps.resolve_vars.outputs) }}' | jq \
            --arg buildcommit "$this_repo_commit" \
            --arg linuxcommit "$(git rev-parse HEAD)" \
            '. += {"build_commit":$buildcommit,"linux_commit":$linuxcommit}' > ../metadata.json

      - name: Configure and build linux
        if: fromJSON(steps.export_metadata.outputs.prev) != fromJSON(steps.export_metadata.outputs.curr)
        working-directory: linux-src
        run: |
          ../configs/${{ steps.resolve_vars.outputs.linux_config }}.sh
          make -j$(getconf _NPROCESSORS_ONLN) bindeb-pkg

      - name: Upload build artifact
        if: fromJSON(steps.export_metadata.outputs.prev) != fromJSON(steps.export_metadata.outputs.curr)
        uses: actions/upload-artifact@v7
        with:
          name: linuxdebs
          path: "*.deb"

      - name: Upload metadata artifact
        uses: actions/upload-artifact@v7
        with:
          name: metadata.json
          path: metadata.json
          archive: false
