name: nightly-rkcombined

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  call_build:
    uses: ./.github/workflows/build.yaml
    with:
      linux_repo: 'https://gitlab.collabora.com/hardware-enablement/rockchip-3588/linux.git'
      linux_ref: 'rockchip-devel'
      linux_arch: 'arm64'
      linux_config: 'rkcombined'
